continue on failure

diff --git a/files/recursive b/files/recursive
--- a/files/recursive
+++ b/files/recursive
@@ -9,7 +9,7 @@ recursive() {
     for subdir in `ls -d ${parent_dir}/*/`; do
         echo $subdir >&2
         cd $subdir
-        $cmd
+        $cmd || echo "failed to perform $cmd" >&2
     done
 }
 
